# Generated by Django 3.2.15 on 2022-11-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_task_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='priority',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='date',
            new_name='dob',
        ),
        migrations.AddField(
            model_name='task',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='phone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='txt',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='vehicle1',
            field=models.BooleanField(default=False, verbose_name='Credit Card'),
        ),
        migrations.AddField(
            model_name='task',
            name='vehicle2',
            field=models.BooleanField(default=False, verbose_name='Debit Card'),
        ),
        migrations.AddField(
            model_name='task',
            name='vehicle3',
            field=models.BooleanField(default=False, verbose_name='Cheque'),
        ),
    ]
