# Generated by Django 3.2.15 on 2022-11-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_auto_20221119_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
