# Generated by Django 3.2.15 on 2022-11-19 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0005_alter_task_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='vehicle1',
        ),
        migrations.RemoveField(
            model_name='task',
            name='vehicle2',
        ),
        migrations.RemoveField(
            model_name='task',
            name='vehicle3',
        ),
        migrations.AddField(
            model_name='task',
            name='materials',
            field=models.CharField(choices=[('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('Cheque', 'cheque')], default=1, max_length=30),
            preserve_default=False,
        ),
    ]
