# Generated by Django 3.2.15 on 2022-11-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0006_auto_20221119_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='account',
            field=models.CharField(choices=[('Savings', 'Savings'), ('Current', 'Current')], default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='subject',
            field=models.CharField(choices=[('Idukii', 'Idukii'), ('Ernakulam', 'Ernakulam'), ('Kollam', 'Kollam')], default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='topic',
            field=models.CharField(choices=[('Devikulam', 'Devikulam'), ('Thodupuzha', 'Thodupuzha'), ('Peerimeedu', 'Peerimeedu'), ('Kuttikanam', 'Kuttikanam'), ('ALuva', 'ALuva'), ('Edapally', 'Edapally'), ('Kothamangalam', 'Kothamangalam'), ('Perumbavoor', 'Perumbavoor'), ('Karunagappally', 'Karunagappally'), ('Kottarakara', 'Kottarakara'), ('Pathanapuram', 'Pathanapuram'), ('Kunnathur', 'Kunnathur')], default=1, max_length=250),
            preserve_default=False,
        ),
    ]
