# Generated by Django 3.2.15 on 2022-11-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0007_auto_20221119_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='materials',
            field=models.BooleanField(choices=[('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('Cheque', 'cheque')], default=False),
        ),
    ]
