# Generated by Django 3.2.15 on 2022-11-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0008_alter_task_materials'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='materialsq',
            field=models.BooleanField(default=False, verbose_name='Cheque'),
        ),
        migrations.AddField(
            model_name='task',
            name='materialss',
            field=models.BooleanField(default=False, verbose_name='Debit Card'),
        ),
        migrations.AlterField(
            model_name='task',
            name='materials',
            field=models.BooleanField(default=False, verbose_name='Credit Card'),
        ),
    ]
